# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Flutter specific rules
    avoid_print: false
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Disable some overly strict rules
    use_build_context_synchronously: false
    avoid_web_libraries_in_flutter: false
